### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/columns-of-cards#1]
Hi! I'm trying to get the columns to all be together so there's no space between them instead of having them all split apart but I can't figure out how to fix that @thomasjbradley

**Comment by thomasjbradley** [comment]
This exercise requires `display: flex` not `display: inline-block`—because Flexbox allows us to remove that space between the elements.

**Comment by heatherlyall** [comment]
I did that and it made all the boxes horizontal, do I just adjust the padding to make it vertical? @thomasjbradley

**Comment by thomasjbradley** [comment]
I’m not sure what you mean…
